### ISSUE TITLE
numStates not defined in main_hmmSPT

### ISSUE THREAD

**Issue by acorbat** [peter-koo/pEMv2#1]
I was testing the script to analyze data of my own and I encountered a problem while testing main_hmmSPT.m. In line 177, numStates is not defined. I copy the line below.

resTimes = cell(numStates,1);

I assumed the value could be obtained by adding the following line
numStates = max(results.state.numberOfStates);

but I haven't thouroughly analyzed the code to know if this is an adequate fix.

**Comment by p-koo** [comment]
The hmm version is still a work in progress (is a bit buggy). You should use pEMv2. We are currently working on pEMv3 (the HMM version), which you should look out for in the future.
